Fix ts_get_now_internal to use transaction time
timescale/timescaledb pull request #2235
Opened 2020-08-20 13:05 UTC by pmwkaa

Related Issue: #2167

Not really sure how to test it, since we not exported this function. I necessary I guess I could make a test c function to wrap it up and then check that the result of it does not change when executed inside an active transaction more then once.

2020-08-20 13:07 UTC, svenklemm requested changes
i think the current behaviour is intentional and not a bug

2020-08-21 05:23 UTC, mkindahl approved these changes

2020-08-25 12:34 UTC, erimatnor commented
FWIW, this now-replacement is used in two places in the continuous aggregate code: first to set the modification time for invalidations in the insert trigger, then in the materializer to calculate the end of the range to materialize. IMO, transaction time makes sense in both of these cases.

2020-08-27 10:50 UTC, pmwkaa commented
@svenklemm any thoughts, suggestions?

2020-08-31 09:38 UTC, svenklemm commented
since caggs seems to be only user of this function i guess its no problem to change it to whatever makes most sense for current caggs

2020-08-31 09:39 UTC, svenklemm approved these changes

2020-08-31 11:47 UTC, merged