Release 1.7.3
timescale/timescaledb pull request #2254
Opened 2020-08-24 15:43 UTC by svenklemm

This maintenance release contains bugfixes since the 1.7.2 release. We deem it high
priority for upgrading.

In particular the fixes contained in this maintenance release address bugs in compression,
drop_chunks and the background worker scheduler.

**Bugfixes**
* #2059 Improve infering start and stop arguments from gapfill query
* #2067 Support moving compressed chunks
* #2068 Apply SET TABLESPACE for compressed chunks
* #2090 Fix index creation with IF NOT EXISTS for existing indexes
* #2092 Fix delete on tables involving hypertables with compression
* #2116 Propagate privileges from hypertables to chunks
* #2150 Lock dimension slice tuple when scanning
* #2164 Fix telemetry installed_time format
* #2184 Fix background worker scheduler memory consumption
* #2222 Fix negative bitmapset member not allowed in decompression

**Thanks**
* @akamensky for reporting an issue with drop_chunks
* @dewetburger430 for reporting an issue with setting tablespace for compressed chunks
* @PichetGoulu for reporting an issue with index creation and IF NOT EXISTS
* @sezaru for reporting an issue with background worker scheduler memory consumption

2020-08-24 17:06 UTC, k-rus reviewed
One minor typo commit was from external contributor. Should he be thanked for this?
https://github.com/timescale/timescaledb/commit/461bcbcea0794db02a2de05e6fbf71be9611b25b

2020-08-26 07:33 UTC, pmwkaa approved these changes

2020-08-26 07:42 UTC, mkindahl commented
> #2116 Propagate privileges from hypertables to chunks

Should be

> #2255 Propagate privileges from hypertables to chunks

This is the 1.7 version of #2116

2020-08-26 07:43 UTC, mkindahl requested changes
> #2116 Propagate privileges from hypertables to chunks

Should be

> #2255 Propagate privileges from hypertables to chunks

This is the 1.7 version of #2116

2020-08-26 07:49 UTC, mkindahl approved these changes
Seems the formatting of the message is off. Otherwise fine.

2020-08-27 07:30 UTC, erimatnor approved these changes
LGTM, just one minor nit.

2020-08-27 07:30 UTC, erimatnor commented on CHANGELOG.md
> +In particular the fixes contained in this maintenance release address bugs in compression,
Nit: I suggest saying "...address issues related to compression..."

Saying "bugs" sounds like there was something wrong with compression while in reality we improved handling of things like setting tablespace.

2020-08-27 08:24 UTC, merged