Migrate ignore_invalidation_older_than for continuous aggregates
timescale/timescaledb pull request #2305
Opened 2020-09-02 16:58 UTC by gayyappan

When the extension is updated to 2.0, we need to migrate
existing ignore_invalidation_older_than settings to the new
continuous aggregate policy framework.

ignore_invalidation_older_than setting is mapped to start_interval
of the refresh policy.If the default setting is used, it is mapped
to NULL start_interval. User provided setting are converted to an
interval value.

2020-09-03 14:40 UTC, erimatnor reviewed
Just a quick comment. Will look more closely later.

2020-09-03 14:43 UTC, gayyappan commented on test/sql/updates/setup.continuous_aggs.v2.sql
> +  IF ts_version < '2.0.0' THEN
Yes, it is. But these are the tests, so don't think it is a concern.

2020-09-08 14:04 UTC, pmwkaa approved these changes
How is it actually tested?

2020-09-09 17:55 UTC, gayyappan commented
> How is it actually tested?

via the extension update tests (test/sql/updates)

2020-09-10 06:47 UTC, svenklemm commented on sql/updates/latest-dev.sql
> +            or ts_tmp_get_time_type( cagg.raw_hypertable_id ) = 'DATE'::regtype
```suggestion
            ts_tmp_get_time_type( cagg.raw_hypertable_id ) IN ('TIMESTAMP','TIMESTAMPTZ','DATE') 
```

2020-09-10 06:49 UTC, svenklemm requested changes
Please simplify expressions

2020-09-10 06:51 UTC, svenklemm commented on sql/updates/latest-dev.sql
> +         )
```suggestion
            ts_tmp_get_time_type( cagg.raw_hypertable_id ) IN ('TIMESTAMP','TIMESTAMPTZ','DATE')
```

2020-09-10 06:53 UTC, svenklemm commented on sql/updates/latest-dev.sql
> +         END
```suggestion
         CASE WHEN ts_tmp_get_time_type(cagg.raw_hypertable_id) IN ('TIMESTAMP','TIMESTAMPTZ','DATE')
            THEN ts_tmp_get_interval(cagg.ignore_invalidation_older_than)::TEXT 
            ELSE cagg.ignore_invalidation_older_than::TEXT 
         END
```

2020-09-10 06:55 UTC, svenklemm commented on sql/updates/latest-dev.sql
> +   END
```suggestion
   CASE WHEN
      ts_tmp_get_time_type(cagg.raw_hypertable_id) IN ('TIMESTAMP','TIMESTAMPTZ','DATE')
      THEN ts_tmp_get_interval(cagg.refresh_lag)::TEXT 
      ELSE cagg.refresh_lag::TEXT 
   END
```

2020-09-11 13:26 UTC, svenklemm approved these changes

2020-09-11 16:51 UTC, merged