Fix outer join qual propagation
timescale/timescaledb pull request #2510
Opened 2020-10-07 17:47 UTC by gayyappan

time_bucket_annotate_walker passes an incorrect status
for outer join to the function that checks quals eligibility
for propagation.

Fixes #2500

2020-10-08 10:59 UTC, svenklemm requested changes
This causes regressions in some of the tests.

2020-10-15 14:04 UTC, svenklemm approved these changes

2020-10-15 17:18 UTC, erimatnor approved these changes

2020-10-15 18:24 UTC, k-rus approved these changes

2020-10-15 18:24 UTC, k-rus commented on test/expected/lateral.out
> +--github issue 2500
This might help to navigate to the issue in GH:
```suggestion
--github issue #2500
```

2020-10-16 12:55 UTC, merged