Replace check function when updating
timescale/timescaledb pull request #2519
Opened 2020-10-09 07:01 UTC by mkindahl

When updating from version 1.5.1 to 1.6.0 the meaning of the
`cascade_to_materialization` column in `bgw_policy_drop_chunks`
changed and `NULL` was introduced as an acceptable value. This means
that the table was updated and `false` in this column was replaced with
`NULL`.

This triggered the check function `valid_ts_interval` to execute as
part of a check constraint. However, it referred to the C version in
the old library and not the new library and therefore triggers an error
in the `ts_extension_check_version` function since the function is in
the old shared library.

This commit fixes the issue by replacing the function definition with
the same function in the new library, so that the check doesn't fail.

Cherry-Pick: 5390cb62

2020-10-09 13:47 UTC, gayyappan approved these changes

2020-10-11 19:08 UTC, svenklemm requested changes
What is this supposed to fix? This should definitely not go into master as there is no ts_valid_ts_interval in master. To affect update from 1.5.1 to 1.6.0 we would have to rerelease those old files and in master valid_ts_interval is already getting dropped due to other refactorings so this change is unnecessary and would actually break further updates

2020-10-12 06:18 UTC, mkindahl commented
> What is this supposed to fix? This should definitely not go into master as there is no ts_valid_ts_interval in master. To affect update from 1.5.1 to 1.6.0 we would have to rerelease those old files and in master valid_ts_interval is already getting dropped due to other refactorings so this change is unnecessary and would actually break further updates

We have the `1.5.1--1.6.0` update script in the tree, so this would now be different between the 1.7 branch and the 2.0 branch unless we update the file to drop the function. I am not entirely sure how this is used, so being better safe then sorry, I expect these file to at least be in sync.

The recommended update path is 1.5.0--1.7.4--2.0.0, which could then potentially cause the check to be invoked before other changes, such as the drop of the function (and the check)? In that case, the update would be blocked. It seems there are update scripts that move directly from 1.5.0 to 2.0.0, but then why do we have the 1.5.1-1.6.0 file there at all?

Either we should remove old update scripts from the directory, or keep them in sync. This change attempts to keep them in sync, but it might be that we shall instead remove the update script.

2020-10-15 14:22 UTC, mkindahl commented
After discussions with @svenklemm it is clear that it should not be there. Closing PR.

2020-10-15 14:22 UTC, closed without merging