Add test to check incremental sort functionality with PG13+
timescale/timescaledb pull request #2928
Opened 2021-02-11 07:28 UTC by nikkhils

Starting with PG13, when a relation is already sorted by
(key1, key2) and we need to sort it by (key1, key2, key3) we can simply
split the input rows into groups having equal values in (key1, key2),
and only sort/compare the remaining column key3.

This commit adds a test for hypertables.

2021-02-11 09:02 UTC, k-rus reviewed
LGTM
I suggest to test that the query results are equivalent between enabled and disabled incremental sort to prevent future regressions if new optimisations will be implemented in TimescaleDB.

2021-02-11 09:20 UTC, nikkhils commented
> LGTM
> I suggest to test that the query results are equivalent between enabled and disabled incremental sort to prevent future regressions if new optimisations will be implemented in TimescaleDB.

Sure. Added actual SELECT queries to run and get the output in both the case.

2021-02-11 11:05 UTC, svenklemm requested changes
This needs more tests, especially interaction with ordered append should be tested

2021-02-11 14:25 UTC, nikkhils commented
> This needs more tests, especially interaction with ordered append should be tested

Added a query which uses incremental sort with `ChunkAppend`

2021-02-11 16:35 UTC, gayyappan approved these changes

2021-02-15 10:52 UTC, svenklemm reviewed
I think you should move this test to regresscheck-shared and try to use the tables already existing in that environment. When testing query output we usually diff the output of optimized/unoptimized output to make the test output itself less noisy.

You can have a look at https://github.com/timescale/timescaledb/blob/master/tsl/test/shared/sql/ordered_append.sql.in for a test doing something like that

2021-02-17 11:41 UTC, nikkhils commented
> I think you should move this test to regresscheck-shared and try to use the tables already existing in that environment. When testing query output we usually diff the output of optimized/unoptimized output to make the test output itself less noisy.
> 
> You can have a look at https://github.com/timescale/timescaledb/blob/master/tsl/test/shared/sql/ordered_append.sql.in for a test doing something like that

@svenklemm I have moved the test to shared directory and used the same format as others. Please take a look.

2021-02-18 11:43 UTC, nikkhils commented
@svenklemm pointed out that "Incremental Sort" plans are already present in other test files. So, adding a small subset here in a new test file does not achieve much in terms of test coverage. So based on that, we are abandoning this PR.

2021-02-18 11:43 UTC, closed without merging