Add option to disable clang-format
timescale/timescaledb pull request #3468
Opened 2021-08-10 07:34 UTC by mkindahl

If `clang-format` is not available, a warning will be given even and
there is no way to disable `clang-format` for automated builds. This
commit turn the `CLANG_FORMAT` into an option so that `clang-format`
can be disabled for automated builds.

2021-08-10 08:40 UTC, svenklemm requested changes
make format is entirely optional for the build process. not sure why we would need an option to enable it since it's sufficient and much more user friendly to check at execution time for the availabilty. this is also much more friendly to packagers.

2021-08-10 08:47 UTC, mkindahl commented
> make format is entirely optional for the build process. not sure why we would need an option to enable it since it's sufficient and much more user friendly to check at execution time for the availabilty. this is also much more friendly to packagers.

If `clang-format` does not exist, a build rule to run `clang-format` using Docker is created instead. We could check for availability of Docker as well and just ignore the situation if docker is not available either, which would indeed be more user-friendly.

However, that raises the issue why we do not do the same when `pg_regress` is not found. In this case, we generate an error and it needs to be explicitly disabled. If user-friendliness is a goal, then we should disable regress tests when `pg_regress` is not found instead of erroring out. (And the same reasoning applies to `pg_isolation_regress`, and TAP tests.)

2021-08-11 08:22 UTC, mkindahl commented
The pull request is updated to by default disable tests if they are not found. It also moves some of the checks for programs to the topmost `CMakeLists.txt`.

2021-08-11 08:28 UTC, mkindahl commented on appveyor.yml
> +    docker exec -it pgregress /bin/bash -c "cd /timescaledb && ./bootstrap -DCMAKE_BUILD_TYPE=Debug -DPG_REGRESS=/usr/local/bin/pg_regress -DTEST_PGHOST=docker.for.win.localhost -DTEST_PGPORT_LOCAL=5
It seems odd to provide a value for `PG_REGRESS` when regress checks are off. Will investigate.

2021-08-11 11:42 UTC, svenklemm approved these changes

2021-08-11 12:24 UTC, mfundul approved these changes

2021-08-11 13:28 UTC, merged