Improve error message when chunk not found
timescale/timescaledb pull request #3610
Opened 2021-09-22 12:25 UTC by mkindahl

When a chunk is not found, we print a generic error message that does
not hint at what we are looking for, which means that it is very hard
to locate the problem.

This commit adds details to the error message printing out values used
for the scan key when searching for the chunk.

Related-To: #2344
Related-To: #3400
Related-To: #153

2021-09-22 12:41 UTC, svenklemm requested changes
This seems to paper over some error message when the real issue is that we are expecting an actual chunk and not a inherited child

2021-09-22 12:49 UTC, mkindahl commented
> This seems to paper over some error message when the real issue is that we are expecting an actual chunk and not a inherited child

This PR is only intended to extend the existing error message "chunk not found" with details so that it is possible to debug the issue (this is more than just the inheritance issue). It does not change when we print these error message.

There are things that we can improve, but I would suggest that we take that as part of the fix for #2344 since this is specific to the issue that you mention above.

2021-09-23 10:22 UTC, afiskon approved these changes

2021-09-27 09:50 UTC, svenklemm approved these changes

2021-09-27 11:01 UTC, merged