Initial release pipeline
timescale/timescaledb pull request #3722
Opened 2021-10-20 12:55 UTC by mkindahl

Initial version of a pipeline that will perform a release based
on a set of commits in a specific branch. The workflow will tag the
release and trigger the release procedure in other repositories, so the
assumption is that the commits for the release and the changelog is up
to date.

You can trigger this workflow either explicitly in the GitHub
interface, or using the CLI with something like:

    gh workflow run release.yaml --ref 2.1.x version=2.1.5

2021-11-09 11:46 UTC, mkindahl commented
One option would be to trigger the release flow on tagging a branch, but that would not allow us to dry-run the release procedure and also would not allow us to test that the tagging part works as expected. This would have to be present in the final release flow, so good to make sure that it works initially as well.

This would replace the step "tagging the release" with `gh workflow run release.yaml --ref 2.5.x version=2.5.1` and eliminate all the following steps in our release procedure.

2021-11-11 10:50 UTC, akuzm approved these changes

2021-11-11 12:19 UTC, afiskon approved these changes

2021-11-23 09:47 UTC, svenklemm requested changes
This probably needs some discussion. I think tagging should be a manual operation. The tagging-workflow says it depends on check-release but this just a noop that does not implement any actual checks.

2023-03-09 06:49 UTC, closed without merging