Silence 3 clang warnings for simple8b_rle.h/dictionary.c
timescale/timescaledb pull request #3788
Opened 2021-11-08 11:07 UTC by afiskon

CLang 11 generates several warnings regarding possible null pointer
dereferences and division by zero. The warnings seem to be false-positive.
However, they may hide new valuable warnings. Thus this patch double-checks
that there is nothing to be concerned about and also silences these warnings.

2021-11-08 11:07 UTC, afiskon commented
The warnings under question:
- https://pastebin.com/NLxcFpAW
- https://pastebin.com/VfL2Hhus
- https://pastebin.com/Gb6dPnNx

2021-11-08 11:12 UTC, svenklemm requested changes
I don't think using asserts to silence warning is the correct thing to do as this will just make them reappear in builds without asserts

2021-11-08 11:18 UTC, afiskon commented
@svenklemm My reasoning was that the asserts don't make things worse for the developers who use debug builds with asserts enabled. The proper fix in this particular case would require much more time investment that personally I don't possess at the moment 🤷‍♂️

2021-11-09 09:14 UTC, mkindahl commented
> The warnings under question:
> 
>     * https://pastebin.com/NLxcFpAW
> 
>     * https://pastebin.com/VfL2Hhus
> 
>     * https://pastebin.com/Gb6dPnNx

These look like clang-tidy warnings, not like clang compiler warnings, so you can probably disable clang-tidy when building (`-DLINTER=OFF`) since it is on by default for CLang builds. However, I see no problem with adding these asserts since they are clearly pre-conditions for the functions and as such just formalize the expectations on the arguments.

2021-11-09 09:14 UTC, mkindahl approved these changes

2021-11-09 10:33 UTC, afiskon commented
@mkindahl Thanks. I would not like to disable clang-tidy since generally, it's useful. These 3 warnings are the only warnings we currently have and when the new one will appear I would like to know about them.

2021-11-11 10:43 UTC, akuzm approved these changes
Probably no harm in adding some precondition asserts. BTW you don't need the "constant on the left" stuff nowadays, every compiler is going to warn you about accidental assignments.

2021-11-11 12:11 UTC, afiskon commented
> you don't need the "constant on the left" stuff nowadays
@akuzm Thanks! Agree, but I noticed that this is used a lot in our code so I decided to follow the existing style.

2021-11-11 12:52 UTC, merged