Fix #3874 invalidate cache in parallel worker to avoid data corruption with VACUUM FULL
timescale/timescaledb pull request #3875
Opened 2021-12-01 07:40 UTC by markrui3

Fix #3874, add extra RelationCacheInvalidate in parallel worker, to avoid data corruption with VACUUM FULL.

2021-12-01 07:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/timescaledb?pullRequest=3875) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/timescaledb?pullRequest=3875) before we can accept your contribution.<br/><hr/>**xiyuan.zr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/timescaledb?pullRequest=3875) it.</sub>

2021-12-02 14:04 UTC, afiskon commented
I can confirm that the proposed patch fixes #3874, and seems to pass `make installcheck` both locally and on CI.

2021-12-02 14:04 UTC, afiskon approved these changes

2021-12-02 14:27 UTC, mfundul commented
I'm sceptical about calling `RelationCacheInvalidate()` in a invalidation callback context. This kind of recursion has created other problems in the past.

2021-12-06 15:11 UTC, mfundul requested changes
https://github.com/timescale/timescaledb/pull/3875#issuecomment-984677177

I think we need a solution that does not issue cache invalidations from within a cache invalidation callback context, since we've seen this causing database corruption before. We need to make sure the fix does not do more damage than what it fixes.

2021-12-10 07:20 UTC, markrui3 commented
> [#3875 (comment)](https://github.com/timescale/timescaledb/pull/3875#issuecomment-984677177)
> 
> I think we need a solution that does not issue cache invalidations from within a cache invalidation callback context, since we've seen this causing database corruption before. We need to make sure the fix does not do more damage than what it fixes.

Could you show the issue that caused database corruption?
In origin code logic, 

```
void
InvalidateSystemCaches(void)
{
	int			i;

	InvalidateCatalogSnapshot();
	ResetCatalogCaches();
	RelationCacheInvalidate();	/* gets smgr and relmap too */

	for (i = 0; i < syscache_callback_count; i++)
	{
		struct SYSCACHECALLBACK *ccitem = syscache_callback_list + i;

		ccitem->function(ccitem->arg, ccitem->id, 0);
	}

	for (i = 0; i < relcache_callback_count; i++)
	{
		struct RELCACHECALLBACK *ccitem = relcache_callback_list + i;

		ccitem->function(ccitem->arg, InvalidOid);
	}
}
```
In my opinion, ccitem->function cannot produce relcahe again, but now timescaledb actually does.

I think the only problem you care is that, alfter I clean relcache again, some varibles that point to the cache may be null pointer. I check the varibles and don't get this problem.

Maybe there is another solution? Like deleting callback as you did in [3a8f396bc7d014a2722b8113236b34b0eda73eec](https://github.com/timescale/timescaledb/commit/3a8f396bc7d014a2722b8113236b34b0eda73eec). Maybe you can give me more details.

2021-12-14 09:37 UTC, mfundul commented
@markrui3 what about if you tried this:
```
--- a/src/cache_invalidate.c
+++ b/src/cache_invalidate.c
@@ -68,6 +68,9 @@ cache_invalidate_callback(Datum arg, Oid relid)
 {
        static bool in_recursion = false;
 
+       if (IsParallelWorker())
+               return;
+
        if (ts_extension_invalidate(relid))
        {
                cache_invalidate_relcache_all();
```
Does this fix the problem?

2021-12-15 11:33 UTC, nikkhils commented
> @markrui3 what about if you tried this:

@mfundul your code snippet does seem to fix the errors/crashes! I will dig in a little bit more to see how and why it does so.

2021-12-16 08:20 UTC, nikkhils commented on src/cache_invalidate.c
> +	cache_invalidate_callback_internal(arg, relid);
We have just renamed this function and are still calling it unconditionally. So I fail to see how this is solving the problem at hand.

2021-12-16 08:20 UTC, nikkhils commented on src/cache_invalidate.c
> +	if (IsParallelWorker())
No need to call `RelationCacheInvalidate` again. It will happen via the PG backend invalidation processing automatically.

2022-01-17 14:54 UTC, afiskon commented
@markrui3 sorry it took look. The team reached the consensus to decline this particular PR because we believe this is not the best solution and will cause new problems eventually. @mfundul is going to work on solving the problem.

2022-01-17 14:54 UTC, closed without merging