Report file name in TestEnsureErrors
timescale/timescaledb pull request #4093
Opened 2022-02-14 10:24 UTC by akuzm

This helps debug C tests.

2022-02-14 13:52 UTC, pmwkaa approved these changes

2022-02-14 15:02 UTC, fabriziomello approved these changes

2022-02-15 21:04 UTC, svenklemm requested changes
This information is already available you can get psql to show it to you by setting VERBOSITY.

```
pgspot@operator[2586389]=> \set VERBOSITY verbose
pgspot@operator[2586389]=> create foo;
ERROR:  42601: syntax error at or near "foo"
LINE 1: create foo;
               ^
LOCATION:  scanner_yyerror, scan.l:1176
Time: 0.631 ms
pgspot@operator[2586389]=>
```

2022-02-16 11:31 UTC, akuzm commented
> This information is already available you can get psql to show it to you by setting VERBOSITY.

Good to know, I'll increase the verbosity then. https://github.com/timescale/timescaledb/pull/4093

2022-02-16 11:32 UTC, closed without merging