Release 2.7.1
timescale/timescaledb pull request #4475
Opened 2022-06-27 15:44 UTC by mkindahl

2022-06-28 07:21 UTC, akuzm commented
These ones are not bug fixes, shouldn't be in a minor release:

[Faster lookup of chunks by point](https://github.com/timescale/timescaledb/pull/4475/commits/d29c6b50b6ef3a5b13ee9798a9a4d70f28d9518d) 
[d29c6b5](https://github.com/timescale/timescaledb/pull/4475/commits/d29c6b50b6ef3a5b13ee9798a9a4d70f28d9518d)

[Mark partialize_agg as parallel safe](https://github.com/timescale/timescaledb/pull/4475/commits/c5bfc440d5c1880250a6d7a1bec7c93250f04b7f) 
[c5bfc44](https://github.com/timescale/timescaledb/pull/4475/commits/c5bfc440d5c1880250a6d7a1bec7c93250f04b7f)

2022-06-28 08:22 UTC, mkindahl commented
> These ones are not bug fixes, shouldn't be in a minor release:
> 
> [Faster lookup of chunks by point](https://github.com/timescale/timescaledb/pull/4475/commits/d29c6b50b6ef3a5b13ee9798a9a4d70f28d9518d) [d29c6b5](https://github.com/timescale/timescaledb/pull/4475/commits/d29c6b50b6ef3a5b13ee9798a9a4d70f28d9518d)
> 
> [Mark partialize_agg as parallel safe](https://github.com/timescale/timescaledb/pull/4475/commits/c5bfc440d5c1880250a6d7a1bec7c93250f04b7f) [c5bfc44](https://github.com/timescale/timescaledb/pull/4475/commits/c5bfc440d5c1880250a6d7a1bec7c93250f04b7f)

Removed them.

2022-07-04 12:05 UTC, akuzm approved these changes

2022-07-04 20:46 UTC, svenklemm requested changes
Need to pull in 02d4aefb8 if you pull in 96202a99b

2022-07-05 06:38 UTC, mkindahl commented
> Need to pull in [02d4aef](https://github.com/timescale/timescaledb/commit/02d4aefb85340dcafea6729141bac033fe3f3ef1) if you pull in [96202a9](https://github.com/timescale/timescaledb/commit/96202a99bdf19f1b459c29d3e12ab42ecf9bc6a5)

It seems to already be there.

> [Fix flaky data_node_bootstrap test](https://github.com/timescale/timescaledb/pull/4475/commits/b204b12698c55dfbd7c163210bc3a098dbb7ee13)

2022-07-05 07:02 UTC, svenklemm commented
> > Need to pull in [02d4aef](https://github.com/timescale/timescaledb/commit/02d4aefb85340dcafea6729141bac033fe3f3ef1) if you pull in [96202a9](https://github.com/timescale/timescaledb/commit/96202a99bdf19f1b459c29d3e12ab42ecf9bc6a5)
> 
> It seems to already be there.
> 
> > [Fix flaky data_node_bootstrap test](https://github.com/timescale/timescaledb/pull/4475/commits/b204b12698c55dfbd7c163210bc3a098dbb7ee13)

Hmm didnt see it in commit list yesterday

2022-07-05 07:04 UTC, mkindahl commented
> > > Need to pull in [02d4aef](https://github.com/timescale/timescaledb/commit/02d4aefb85340dcafea6729141bac033fe3f3ef1) if you pull in [96202a9](https://github.com/timescale/timescaledb/commit/96202a99bdf19f1b459c29d3e12ab42ecf9bc6a5)
> > 
> > 
> > It seems to already be there.
> > > [Fix flaky data_node_bootstrap test](https://github.com/timescale/timescaledb/pull/4475/commits/b204b12698c55dfbd7c163210bc3a098dbb7ee13)
> 
> Hmm didnt see it in commit list yesterday

It has a different commit hash.

2022-07-05 07:08 UTC, svenklemm commented
Did you run pgspot on the downgrade script i dont think your reverse dev modifications are secure.

2022-07-05 07:09 UTC, mkindahl commented
> Did you run pgspot on the downgrade script i dont think your reverse dev modifications are secure.

Doesn't the `pgspot` GH action run it on downgrade scripts?

2022-07-05 12:31 UTC, mkindahl commented
> > 
> 
> Hmm I think this should be reversed. I think reverse-dev should not be modified unless necessary when cherry-picking as those modifications get much less review and your modifications introduce potential security vulnerabilities. In this specific case it's not exploitable but it might be in others.

Well, the downgrade tests fail because functions are defined here that causes conflicts with the fetched files from the previous version. Functions should just be dropped in the reverse-dev file and the the functions be defined the normal way in the epilogue.

It's the last commit. If you have suggestions for fixes, please add them and I will incorporate them.
 
> pgspot does run on downgrade script but i'd have to do a more thorough investigation to check if it catches this specific case properly in a release-branch.

2022-07-07 15:40 UTC, merged