Add indexes to job_errors table
timescale/timescaledb pull request #4812
Opened 2022-10-11 10:19 UTC by konskov

This commit adds two indexes to the job_errors table. One index on job_id to make filtering by job_id faster, and one on the finish_time of the failed job, as the retention job for the job_errors table selects which records to drop based on the value of finish_time.

2022-10-11 16:55 UTC, fabriziomello commented
You didn't add DROP INDEX into reverse-dev.sql because it was not released yet and in your previous PR you added a DROP TABLE right??? 

Would be nice to add to comments that this PR (and in the commit message) is related to the previous one where you introduce the `job_errors` table.

2022-10-11 16:56 UTC, fabriziomello approved these changes

2022-11-10 10:06 UTC, akuzm approved these changes

2023-03-17 07:44 UTC, kgyrtkirk commented on sql/updates/latest-dev.sql
> +-- don't need to drop indexes in reverse-dev because the table itself is dropped
I don't think that's true anymore; this patch have lost that train :)

2023-03-22 19:45 UTC, fabriziomello requested changes
Need to include reverse-dev.sql to remove indexes.

2024-04-09 08:00 UTC, svenklemm commented
closing since its outdated

2024-04-09 08:00 UTC, closed without merging