Remove CentOS from the platforms list
timescale/timescaledb pull request #5149
Opened 2023-01-04 20:57 UTC by jfjoly

Signed-off-by: JF Joly <jfjoly@users.noreply.github.com>

2023-01-05 06:53 UTC, jnidzwetzki commented on README.md
> +    - [RedHat](https://tsdb.co/GitHubTimescaleRedHatCentOS)
Nit: Maybe we should change the name of the redirect as well (`GitHubTimescaleRedHatCentOS`)

2023-01-05 06:53 UTC, jnidzwetzki approved these changes

2023-01-05 10:56 UTC, svenklemm requested changes
Why are we changing this? We are still building packages for CentOS

2023-01-26 18:44 UTC, Tenorotti commented
nudging this to get it reviewed and approved

2023-03-27 09:13 UTC, svenklemm commented
> nudging this to get it reviewed and approved

We are still using Centos 7 to build our RedHat packages for that version so the change is incorrect IMO.

2023-09-27 07:37 UTC, closed without merging