Compression can't be enabled on MVs when segmentby/orderby columns need quotation
timescale/timescaledb pull request #5290
Opened 2023-02-06 16:52 UTC by kgyrtkirk

consider the sql commands:
```
drop table if EXISTS "tEst2" ;
-- Creating hypertable
CREATE TABLE IF NOT EXISTS "tEst2" (
    "Id" uuid NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    CONSTRAINT "test2_pkey" PRIMARY KEY ("Id", "Time")
);

SELECT create_hypertable(
  '"tEst2"',
  'Time',
  chunk_time_interval => INTERVAL '1 day'
);

alter table "tEst2" set (timescaledb.compress=true, timescaledb.compress_segmentby='"Id"');

DROP MATERIALIZED VIEW if EXISTS "tEst2_mv";

CREATE MATERIALIZED VIEW "tEst2_mv"
WITH (timescaledb.continuous) AS
SELECT "Id" as "Idd",
   time_bucket(INTERVAL '1 day', "Time") AS "bUcket"
FROM public."tEst2" 
GROUP BY "Idd", "bUcket";

ALTER MATERIALIZED VIEW "tEst2_mv" SET (timescaledb.compress = true);
```

before this patch the last command failed because:
* the `Idd` column lost quotation; leading to `ERROR:  column "idd" does not exist` 
* or the `bUcket` column lost quotation; leading to `ERROR:  column "bucket" does not exist`

2023-02-06 17:07 UTC, svenklemm requested changes
doing `DROP IF EXISTS` is not necessary in tests since they each run in dedicated databases

2023-02-06 17:11 UTC, kgyrtkirk commented
@svenklemm done

2023-02-07 05:05 UTC, akuzm approved these changes

2023-02-07 07:15 UTC, mkindahl approved these changes

2023-02-07 14:50 UTC, svenklemm approved these changes

2023-02-07 20:01 UTC, merged