Fix chunk status update in catalog table
timescale/timescaledb pull request #5418
Opened 2023-03-09 09:18 UTC by sb230132

When INSERT and COMPRESS/RECOMPRESS are run in parallel, chunk status in CHUNK catalog table is not updated correctly. This patch fixes this issue.

Fixes #5389

2023-03-09 09:47 UTC, konskov commented on src/nodes/chunk_dispatch/chunk_insert_state.c
> +	if (ts_chunk_is_compressed(chunk))
```suggestion
	if (ts_chunk_is_compressed(chunk) && !ts_chunk_is_partial(chunk))
```

2023-03-09 09:48 UTC, konskov commented on src/nodes/chunk_dispatch/chunk_dispatch.c
> +	if (IsolationUsesXactSnapshot())
```suggestion
	if (IsolationUsesXactSnapshot() || IsolationIsSerializable())
```

2023-03-09 10:27 UTC, antekresic commented
This change might address the issue with decompression as well: #5419 

We could just add another isolation tests with decompression to confirm.

2023-03-11 13:09 UTC, svenklemm requested changes
This will make operations on a hypertable block operations on all other hypertables which we want to avoid.

2023-04-12 11:03 UTC, antekresic commented
This can be closed as duplicate of #5533

2023-04-21 06:59 UTC, antekresic commented
Closing since the issue is already fixed with different PR.

2023-04-21 06:59 UTC, closed without merging