Update debian/ubuntu versions
timescale/timescaledb pull request #5859
Opened 2023-07-05 09:22 UTC by kgyrtkirk

Add: Debian 12, Ubuntu 23.04
Remove: Debian 10, Ubuntu 22.10
Change references to use version numbers instead of release names.

2023-07-06 13:29 UTC, pmwkaa approved these changes

2023-07-07 09:19 UTC, svenklemm commented
Changing this requires a bit more work and needs to be coordinated across multiple repositories. We need to make sure the complete infrastructure is set up correctly for the new platforms and the packages have been built and published. Since this check only runs nightly it would be good to temporarily enable this for this PR so we can see whether all the requirements are there.

2023-07-07 09:29 UTC, svenklemm requested changes
You need to make sure the packages for those new platforms have been published before merging this otherwise this will be broken in CI

2023-07-07 09:53 UTC, svenklemm commented
The PR by itself looks good but some work outside of this repository has to be done first before it can be merged.

2023-09-26 16:11 UTC, closed without merging