Add metadata for chunk creation time
timescale/timescaledb pull request #6062
Opened 2023-09-12 07:54 UTC by pdipesh02

- Added creation_time attribute to timescaledb catalog table "chunk". Also, updated corresponding view timescaledb_information.chunks to include chunk_creation_time attribute.
- A newly created chunk is assigned the creation time during chunk creation to handle new partition range for give dimension (Time/ SERIAL/BIGSERIAL/INT/...).
- In case of an already existing chunk, the creation time is updated as part of running upgrade script. The current timestamp (now()) at the time of upgrade has been assigned as chunk creation time.
- Similarly, downgrade script is updated to drop the attribute creation_time from catalog table "chunk".
- All relevant queries/views/test output has been updated accordingly.

2023-09-12 09:19 UTC, svenklemm requested changes
Please dont use ADD COLUMN/DROP COLUMN in update/downgrade scripts

2023-09-15 11:15 UTC, nikkhils commented on sql/updates/latest-dev.sql
> +    creation_time = (pg_catalog.pg_stat_file(pg_catalog.pg_relation_filepath(r.oid))).change
to keep things simple, I decided to use the `modification` time here. In append only workloads, this should be a decent approximation I guess.

2023-09-15 11:27 UTC, nikkhils commented on test/sql/create_hypertable.sql
> +\d timescaledb_information.chunks
ack

2023-09-15 11:29 UTC, nikkhils commented on test/sql/information_views.sql
> +FROM timescaledb_information.chunks WHERE hypertable_name = 'ht1' ORDER BY chunk_name;
I will shift the 

`\d timescaledb_information.chunks`
here, to capture the addition of a new column and THEN we can use this explicit list as above

2023-09-15 11:32 UTC, nikkhils commented on test/sql/tablespace.sql
> +ORDER BY chunk_name;
sure, done.

2023-09-15 11:34 UTC, nikkhils commented on test/sql/updates/post.catalog.sql
> +SELECT id, hypertable_id, schema_name, table_name, compressed_chunk_id, dropped, status, osm_chunk
done

2023-09-27 09:03 UTC, nikkhils commented on sql/pre_install/tables.sql
> +  creation_time timestamptz NOT NULL,
@fabriziomello ah, a bit too late I think for this :-)

2023-09-27 14:21 UTC, mkindahl approved these changes

2023-09-29 20:29 UTC, fabriziomello commented on sql/pre_install/tables.sql
> +  creation_time timestamptz NOT NULL,
I have a commit locally doing that... if you want I can push to this branch and then you evaluate if accept or discard it!

2023-10-01 20:11 UTC, svenklemm commented on sql/pre_install/tables.sql
> +  creation_time timestamptz NOT NULL,
While we are rebuilding chunk table we could move around the fields a bit to save some bytes due to type alignments. e.g. move status after compressed_chunk_id and creation_time before the bool fields. Bool fields are 1-byte aligned, int fields are 4-byte aligned and timestamptz fields are 8-byte aligned.

2023-10-01 20:12 UTC, svenklemm approved these changes

2023-10-03 06:59 UTC, nikkhils commented on sql/pre_install/tables.sql
> +  creation_time timestamptz NOT NULL,
@fabriziomello I think this is a very subjective preference :-)

2023-10-03 13:03 UTC, nikkhils commented on sql/pre_install/tables.sql
> +  creation_time timestamptz NOT NULL,
@svenklemm I tried moving fields around but it causes a lot of instability in the diffs. So maybe we can do this later.

2023-10-04 09:19 UTC, merged