Add table mappings to compression settings
timescale/timescaledb pull request #6990
Opened 2024-06-03 11:17 UTC by erimatnor

Refactor the compression settings metadata table to include a mapping from a chunk's relid to its compressed chunk's relid.

Adding this mapping makes compression settings the main metadata table for compression-related information, while decoupling it from chunk metadata. This simplifies the code that looks up compression metadata as it no longer requires first looking up the corresponding compressed chunk.

The new compression settings is a step towards removing a chunk's compression table from the chunk metadata. In other words, the "compressed chunk" will no longer be a chunk, just a relation associated with the regular chunk via compression settings.

2024-06-06 03:45 UTC, svenklemm requested changes
It looks like this PR might need a bit more work. If we're going to store info about compressed and uncompressed assignments in the compression_settings table, we should take it out of the chunk catalog table in this same update. Storing the same thing in two places can lead to confusion and mistakes. We want to keep things tidy and have one source of truth for this information.

2024-06-07 16:07 UTC, erimatnor commented
> It looks like this PR might need a bit more work. If we're going to store info about compressed and uncompressed assignments in the compression_settings table, we should take it out of the chunk catalog table in this same update. Storing the same thing in two places can lead to confusion and mistakes. We want to keep things tidy and have one source of truth for this information.

While I agree we should get rid of the metadata in the chunk catalog table, I think we should do this in increments. That's a pretty heavy lift and has other consequences on dependent tables, like compression_chunk_size, etc.

This change does not mean we will store the same information in multiple places apart from an extra ID. I think we can live with this in the short term until the other changes are merged too.

2024-06-11 10:11 UTC, antekresic reviewed
For posterity, lets make a concrete plan for the rest of the refactoring that should follow this PR for clarity and prioritization purposes.

Removing the compressed_chunk_id chunk metadata should be followed up and would clean up the catalog and our code nicely.

2024-06-11 10:11 UTC, antekresic commented on src/ts_catalog/compression_settings.c
> +ts_compression_settings_get_by_compress_relid(Oid relid)
Add a todo to make clear this will eventually go away since its an intermediate step towards the complete refactor.

2024-06-11 10:11 UTC, antekresic commented on tsl/src/compression/compression.c
> +	comp_chunk = ts_chunk_get_by_id(chunk->fd.compressed_chunk_id, true);
Can you get the compressed table relid from the settings instead of getting the compressed chunk metadata here?

2025-01-29 10:06 UTC, erimatnor commented on src/ts_catalog/compression_settings.c
> +ts_compression_settings_get_by_compress_relid(Oid relid)
I think there's at least one case where it is needed, which is when merging into an existing chunk during compression. Probably, we can make it go away, but I am not 100% sure at this point.

2025-01-29 10:08 UTC, erimatnor commented on tsl/src/compression/compression.c
> +	comp_chunk = ts_chunk_get_by_id(chunk->fd.compressed_chunk_id, true);
Yes!, and there are probably more places like this with some more refactoring in follow up PRs.

2025-01-29 10:09 UTC, erimatnor commented on src/ts_catalog/compression_settings.c
> +ts_compression_settings_delete_by_compress_relid(Oid relid)
I would love for it to go away, but I am not 100% confident that it is possible. For example, if we clean up settings due to a "drop event trigger", we might get the relid of the compressed relation and need to clean it up.

2025-01-29 10:13 UTC, erimatnor commented on src/process_utility.c
> +		ts_compression_settings_rename_column_recurse(ht->main_table_relid,
Changed.

2025-01-29 10:18 UTC, erimatnor commented
> For posterity, lets make a concrete plan for the rest of the refactoring that should follow this PR for clarity and prioritization purposes.

Here's the plan: https://github.com/timescale/eng-database/issues/618

> 
> Removing the compressed_chunk_id chunk metadata should be followed up and would clean up the catalog and our code nicely.

100%. Already working on this, but it is a much bigger change so probably requires multiple follow up PRs. Next step is to remove unnecessary fields in compression_chunk_size, for example.

2025-01-29 10:23 UTC, erimatnor commented
> Storing the same thing in two places can lead to confusion and mistakes. We want to keep things tidy and have one source of truth for this information.

@svenklemm I agree with single source of truth. However, we already have places were we duplicate information (chunk Ids), like compression_chunk_size, for example. 

The intention is to address this over multiple refactoring PRs, including getting rid of compressed chunks in the "chunk" table. But his is further down the line and this is just the first step.  I do think it is important to make these changes incrementally. Doing everything in one PR will lead to massive changes and it will be very difficult to review.

2025-01-30 10:19 UTC, mkindahl approved these changes
This is a good step in the direction of avoiding unnecessary lookup of catalog data.

From some of the changes made here I see that we still have a lot of unnecessary indirection causing us to add extraneous updates of catalog data, e.g., attribute names, so we are far from done.

2025-01-30 10:19 UTC, mkindahl commented on src/ts_catalog/compression_settings.c
> +}
This function seems redundant. It is just as easy to call `compression_settings_delete` directly and is just as clear.

2025-01-30 10:19 UTC, mkindahl commented on src/ts_catalog/compression_settings.c
> +	return compression_settings_delete(relid, false);
This function seems redundant. It is just as easy to call `compression_settings_delete` directly.

2025-01-30 10:19 UTC, mkindahl commented on src/ts_catalog/compression_settings.c
> +}
Just an observation: This looks like we are using named columns rather than attribute number to reference columns, which requires us to have these kinds of functions. It would be better to just use the attribute number directly in all our tables, but I do not think this is something that should be done as part of this PR.

It is essentially an additional indirect lookup layer for the attributes, just like the one we currently have for our catalogs because we have our own chunk and hypertable identifiers.

2025-01-30 11:39 UTC, erimatnor commented on sql/pre_install/tables.sql
> +  relid regclass NOT NULL,
The relid can be a hypertable as well, and in the future maybe we can compress regular tables too.

2025-01-30 11:40 UTC, erimatnor commented on src/chunk.c
> +	}
No, its not a metadata problem. When we decompress, we drop the compressed table so in that case we drop the "compressed" chunk but not the "non-compressed" chunk.

2025-01-30 11:43 UTC, erimatnor commented on src/ts_catalog/compression_settings.c
> +}
When reading the code, it is not clear what "true" means, so I think having a good name is more clear IMO. If you feel strongly about it I can remove the function.

2025-01-30 14:55 UTC, erimatnor commented on src/ts_catalog/compression_settings.c
> +	return compression_settings_delete(relid, false);
Answered above.

2025-02-21 11:09 UTC, antekresic approved these changes

2025-02-21 11:24 UTC, erimatnor commented on tsl/src/compression/compression.c
> +	CompressionSettings *settings = ts_compression_settings_get_by_compress_relid(out_table);
I think the issue here is that `in_table`  might not have compression settings at all since it is a plain table, and, in the merge case, we never create a compressed chunk for it since we are merging it into an existing one.

2025-02-21 15:19 UTC, svenklemm approved these changes

2025-02-24 10:48 UTC, merged