Improve release-notes further
timescale/timescaledb pull request #7121
Opened 2024-07-12 10:53 UTC by pallavisontakke

For docs-compliance for the upcoming release.

2024-07-12 11:02 UTC, svenklemm approved these changes

2024-07-12 11:08 UTC, billy-the-fish requested changes

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/fix_7055
> +Fixes: #7055: Fix the `scankey` for `segment by` columns, where constant type is different from variable.
```suggestion
Fixes: #7055: Fix the `scankey` for `segment by` columns, where the type `constant` is different to `variable`.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/fix_7064
> +Fixes: #7064: Fix the bug in default `order by` calculation in compression.
```suggestion
Fixes: #7064: Fix the bug in the default `order by` calculation in compression.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/fix_7074
> +Fixes: #7074: Fix the bug in default `segment by` calculation in compression.
```suggestion
Fixes: #7074: Fix the bug in the default `segment by` calculation in compression.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_6880
> +Implements: #6880: Add support for the array operators to compressed DML batch filtering.
```suggestion
Implements: #6880: Add support for the array operators used to compressed DML batch filtering.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_6897
> +Implements: #6897: Add support for replica identity on the compressed hypertables.
```suggestion
Implements: #6897: Add support for replica identity on compressed hypertables.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_6918
> +Implements: #6918: Remove the support for PG13.
```suggestion
Implements: #6918: Remove support for PG13.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_6989
> +Implements: #6989: Add support for the foreign keys from plain tables to hypertables.
```suggestion
Implements: #6989: Add support for foreign keys when converting plain tables to hypertables.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_7018
> +Fixes: #7018: Fix the `search_path` quoting in the compression defaults function.
```suggestion
Fixes: #7018: Fix `search_path` quoting in the compression defaults function.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_7046
> +Fixes: #7046: Prevent locking the compressed tuples.
```suggestion
Fixes: #7046: Prevent locking for compressed tuples.
```

2024-07-12 11:08 UTC, billy-the-fish commented on .unreleased/pr_7048
> +Implements: #7048: Add the index scan to INSERT DML decompression.
```suggestion
Implements: #7048: Add an index scan for INSERT DML decompression.
```

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_6880
> +Implements: #6880: Add support for the array operators to compressed DML batch filtering.
Edited so.

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_6897
> +Implements: #6897: Add support for replica identity on the compressed hypertables.
Edited so.

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_6918
> +Implements: #6918: Remove the support for PG13.
Edited so.

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_6880
> +Implements: #6880: Add support for the array operators to compressed DML batch filtering.
Edited so.

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_6989
> +Implements: #6989: Add support for the foreign keys from plain tables to hypertables.
Edited so.

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_7018
> +Fixes: #7018: Fix the `search_path` quoting in the compression defaults function.
Edited so.

2024-07-12 12:27 UTC, pallavisontakke commented on .unreleased/pr_7046
> +Fixes: #7046: Prevent locking the compressed tuples.
Edited so.

2024-07-12 12:28 UTC, pallavisontakke commented on .unreleased/pr_7048
> +Implements: #7048: Add the index scan to INSERT DML decompression.
Edited so.

2024-07-15 07:03 UTC, billy-the-fish approved these changes
LGTM

2024-07-15 07:13 UTC, merged