Add function and test to show dictionary encoding
timescale/timescaledb pull request #7126
Opened 2024-07-14 17:57 UTC by mkindahl

Add a function that can be used on a compressed data value to show some metadata information, such as the compression algorithm used and the presence of any null values.

2024-07-16 07:19 UTC, mkindahl commented
> Useful function, let's call it somewhere in `compression_algos` so that it's covered. Should it be debug-only like the other test functions?

Yes, the tests we added were using Hyperstore, so I'll add tests for it in `compression_algos`. We don't really have a good place for utility functions and I am reluctant to place it in `public`, but maybe that is ok?

2024-07-16 13:27 UTC, fabriziomello commented on tsl/src/compression/compression.c
> +{
Looks like we need some tests

2024-07-27 18:02 UTC, fabriziomello requested changes
We're adding some code that is not covered by any test. Is it very difficult to introduce some tests?

2024-07-29 10:23 UTC, mkindahl commented
> We're adding some code that is not covered by any test. Is it very difficult to introduce some tests?

Nope. Based on the feedback from @akuzm I intended to add tests. Mostly wondering if there is anything else that needs to be dealt with.

2024-08-05 15:34 UTC, fabriziomello approved these changes

2024-08-05 15:34 UTC, merged