Release 2.16.0
timescale/timescaledb pull request #7156
Opened 2024-07-25 13:48 UTC by pallavisontakke

This release contains performance improvements and bug fixes since the 2.15.3 release. We recommend that you upgrade at the next available opportunity.

**Features**
* #6880: Add support for the array operators used for compressed DML batch filtering.
* #6895: Improve the compressed DML expression pushdown.
* #6897: Add support for replica identity on compressed hypertables.
* #6918: Remove support for PG13.
* #6920: Rework compression activity wal markers.
* #6989: Add support for foreign keys when converting plain tables to hypertables.
* #7020: Add support for the chunk column statistics tracking.
* #7048: Add an index scan for INSERT DML decompression.
* #7075: Reduce decompression on the compressed INSERT.
* #7101: Reduce decompressions for the compressed UPDATE/DELETE.
* #7108: Reduce decompressions for the INSERTs with UNIQUE constraints.
* #7116: Use DELETE instead of TRUNCATE after compression.
* #7134: Refactor foreign key handling for compressed hypertables.

**Bugfixes**
* #7018: Fix `search_path` quoting in the compression defaults function.
* #7046: Prevent locking for compressed tuples.
* #7055: Fix the `scankey` for `segment by` columns, where the type `constant` is different to `variable`.
* #7064: Fix the bug in the default `order by` calculation in compression.
* #7069: Fix the index column name usage.
* #7074: Fix the bug in the default `segment by` calculation in compression.

2024-07-25 14:49 UTC, iroussos approved these changes
Thank you @pallavisontakke - added some final small changes on the changelog based on feedback by Ramon. 

Approving on my end - no further comments other than this change

2024-07-25 14:49 UTC, iroussos commented on CHANGELOG.md
> +  between multiple regular tables.
Adding some small changes based on feedback by Ramon

```suggestion
This release contains significant performance improvements when working with compressed data, extended join
support in continuous aggregates, and the ability to define foreign keys from regular tables towards hypertables.
We recommend that you upgrade at the next available opportunity.

In TimescaleDB v2.16.0 we:

* Introduce multiple performance focused optimizations for data manipulation operations (DML) over compressed chunks. 

  Improved upsert performance by more than 100x in some cases and more than 1000x in some update/delete scenarios.

* Add the ability to define sparse indexes on non-partitioning columns of compressed hypertables

  TimescaleDB v2.16.0 extends chunk exclusion to use those sparse indexes when queries filter on the relevant columns, 
  and prune chunks that do not include any relevant data for calculating the query response.

* Offer new options for use cases that require foreign keys defined.

  You can now add foreign keys from regular tables towards hypertables. We have also removed
  some really annoying locks in the reverse direction that blocked access to referenced tables
  while compression was running.

* Extend Continuous Aggregates to support more types of analytical queries.

  More types of joins are supported, additional equality operators on join clauses, and
  support for joins between multiple regular tables.
```

2024-07-25 18:38 UTC, iroussos requested changes
Adding a review comment requesting changes to block from accidentally merging - we need to do one last change before we can move forward with 2.16

Internal discussion for more information:
https://iobeam.slack.com/archives/C060QFPDQPM/p1721932110641679

2024-07-26 08:05 UTC, pallavisontakke commented on CHANGELOG.md
> +  between multiple regular tables.
Alright, edited so.

2024-07-26 08:09 UTC, closed without merging