PG17: Enable ABI on CI
timescale/timescaledb pull request #7312
Opened 2024-10-01 14:15 UTC by fabriziomello

Also bump alpine images from 3.18 to 3.19 since last minor PG releases are not available on 3.18 anymore.

2024-10-02 08:50 UTC, svenklemm approved these changes

2024-10-03 08:59 UTC, antekresic approved these changes

2024-10-05 05:46 UTC, svenklemm requested changes
This does not fix the problem at all and just papers over it. ABI tests is a canary of future changes and we need to fix the cagg code to work with these.

2024-10-05 13:00 UTC, fabriziomello commented
> This does not fix the problem at all and just papers over it. ABI tests is a canary of future changes and we need to fix the cagg code to work with these.

Yep... I'm doing it in other PR: https://github.com/timescale/timescaledb/pull/7319

2024-10-07 17:12 UTC, svenklemm approved these changes

2024-10-07 17:30 UTC, merged