Add index creation on orderby columns
timescale/timescaledb pull request #7436
Opened 2024-11-12 23:53 UTC by kpan2034

Previously, for chunks without a segmentby column specified in the compression settings, no indexes were created. This change allows indexes to be created on orderby columns only in this scenario.

2024-11-19 09:24 UTC, antekresic commented
Lets make sure we don't run segmentwise recompression on chunks without segmentby because currently its suboptimal vs doing a full recompress.

2024-11-26 12:45 UTC, antekresic requested changes
Lets disable segmentwise recompression for these chunks for now, until we can optimize it in the near future.

2025-01-13 08:37 UTC, antekresic approved these changes
Approved but I think we need to add a comment on why we are disabling segmentwise recompression for these certain chunks (even if it is temporary).

2025-01-13 08:37 UTC, antekresic commented on tsl/src/compression/api.c
> +	if (num_segmentby == 0)
This needs a comment why we are doing this.

2025-01-13 23:08 UTC, svenklemm approved these changes

2025-01-14 15:08 UTC, merged