Call InitResultRelInfo in ts_catalog_open_indexes
timescale/timescaledb pull request #7447
Opened 2024-11-15 06:47 UTC by mkindahl

Because a new member was added to `ResulRelInfo` in 17.1, our initialization of `resultRelInfo` in `ts_catalog_open_indexes` did not work correctly. Instead with should call `InitResultRelInfo` with the information.

2024-11-15 07:34 UTC, erimatnor commented
Why do we even have this functions when PG has https://github.com/postgres/postgres/blob/91f20bc2f7e4fcf5de5c65a6cb1190e0afa91c0b/src/backend/catalog/indexing.c#L43?

OTOH, that function also doesn't call InitResultRelInfo.

2024-11-15 07:37 UTC, mkindahl commented
> Why do we even have this functions when PG has https://github.com/postgres/postgres/blob/91f20bc2f7e4fcf5de5c65a6cb1190e0afa91c0b/src/backend/catalog/indexing.c#L43?
> 
> OTOH, that function also doesn't call InitResultRelInfo.
> 
> In fact, we also call `CatalogOpenIndexes` directly in our code so it is kind of confusing.

Good point, we should probably use that function directly instead. Will investigate.

2024-11-15 09:59 UTC, akuzm approved these changes

2024-11-15 14:45 UTC, afiskon approved these changes

2024-11-15 15:09 UTC, erimatnor commented on .unreleased/pr_7447
> +Fixes: #7447 Call InitResultRelInfo in ts_catalog_open_indexes
This seems out-of-date

2024-11-15 15:09 UTC, erimatnor commented on src/nodes/chunk_dispatch/chunk_insert_state.c
> +#define makeNode(_type_) ((_type_ *) newNode(2 * sizeof(_type_), T_##_type_))
Yupp, this is indeed horrible, as you put it.

2024-11-15 15:13 UTC, erimatnor commented on tsl/src/compression/compression.c
> +		union OverallocatedResultRelInfo
Why do we even need this to be stack allocated? Isn't it better to just heap-allocate it as that would be safer given that palloc already over-allocates? Or, if we are not satisfied with that, we can just give palloc a bigger size.

2024-11-15 15:18 UTC, erimatnor commented on src/nodes/chunk_dispatch/chunk_insert_state.c
> +#define makeNode(_type_) ((_type_ *) newNode(2 * sizeof(_type_), T_##_type_))
Why do we need it? The palloc code alloced 512 byte chunks, which should be enough as explained here: https://www.postgresql.org/message-id/1972733.1731612633%40sss.pgh.pa.us

2024-11-15 15:39 UTC, mkindahl commented on .unreleased/pr_7447
> +Fixes: #7447 Call InitResultRelInfo in ts_catalog_open_indexes
Fixed.

2024-11-16 01:04 UTC, mfreed commented
Let's hold off on any merge while we review the planned changes in the out-of-cycle Postgres release:

https://www.postgresql.org/about/news/out-of-cycle-release-scheduled-for-november-21-2024-2958/

2024-11-16 09:00 UTC, mkindahl commented
One issue remains to investigate, that of using arrays of `ResultRelInfo` structures that is present in `ExecModifyTable`.

2024-11-18 08:49 UTC, mkindahl commented
This was now [fixed upstreams](https://github.com/postgres/postgres/commit/6bfacd368bb4ae3bd53b2692fee98797a771082a) and a patch is not necessary to solve this immediate problem. However, these changes would protect us against similar problem in future versions.

2024-11-18 09:51 UTC, svenklemm requested changes
I think we are overshooting the target here, upstream will fix this and do 17.2 so we should just require 17.2 as minimum version (and equivalent for other majors). There is no reason to create overallocated resultrelinfo. Stuff compiled against 17.0 should even work with 17.2 if i understand correctly.

2024-11-19 10:30 UTC, mkindahl commented
Closing issue since we have a 17.2 release that will deal with the problems.

2024-11-19 10:30 UTC, closed without merging