Allow DROP NOT NULL on column of compressed table
timescale/timescaledb pull request #7455
Opened 2024-11-18 19:25 UTC by mkindahl

Remove the restriction on `ALTER TABLE ... ALTER COLUMN SET/DROP NOT NULL` on compressed tables.

Dropping or setting the `NOT NULL` constraint on a column of a compressed table is safe since it does not require re-writing any data. Setting `NOT NULL` will require a full table scan to verify that there are no NULL in the table.

Fixes #5776

2024-11-19 07:42 UTC, mkindahl commented
It is actually fine to use `SET NOT NULL` as well. It will generate a full table scan to investigate if there are any NULL present, but otherwise it should not require any dramatic changes.

2024-11-19 07:55 UTC, mkindahl commented on tsl/test/expected/compression_ddl.out
> +SELECT count(compress_chunk(ch)) FROM show_chunks('test2') ch;
No, that is not tested. It tests that the inserted value (which ends up in the WS) can be found before and after compression, but it does not decompress the entire chunk.

2024-11-19 07:56 UTC, erimatnor approved these changes

2024-11-19 08:47 UTC, antekresic requested changes
Setting `NOT NULL` on a column which has compressed NULL values doesn't work properly. Maybe we should just limit this change to dropping `NOT NULL` since setting requires decompression which isn't done in the current change.

Also, lets add a test for this, trying to set `NOT NULL` on a column which has NULL values and the hypertable is full compressed (not partial).

2024-11-19 15:48 UTC, mkindahl commented
> Setting `NOT NULL` on a column which has compressed NULL values doesn't work properly. Maybe we should just limit this change to dropping `NOT NULL` since setting requires decompression which isn't done in the current change.

Yeah, I discovered that it does not work for compressed tables using the `heap` access method, but this works fine for chunks with the `hypercore` access method (since it looks like a normal hypertable). Added checks so that we only allow this for compressed chunks that are using `hypercore` table access method.

> Also, lets add a test for this, trying to set `NOT NULL` on a column which has NULL values and the hypertable is full compressed (not partial).

There is an existing test in `compression_errors`, but that does not compress the table, so the question is if we should check the flag on the hypertable (and ignore the status of the chunks), or if we should allow this with the compression flag set and chunk fully decompressed.

2024-11-19 16:43 UTC, feikesteenbergen commented
Could we get the simplest thing merged the `DROP NOT NULL`? the rest is also useful, but easier to workaround for users

2024-11-19 17:08 UTC, mkindahl commented
> Could we get the simplest thing merged the `DROP NOT NULL`? the rest is also useful, but easier to workaround for users

Ok, split out the code to deal with `SET NOT NULL` into #7463 and left the other pull request here. Still awaiting reviews.

2024-11-20 08:47 UTC, antekresic approved these changes

2024-11-20 09:06 UTC, mkindahl commented
> I guess my approval was for a different PR. I approve also this PR, but with some pause.
> 
> I am not 100% sure it is a good idea to allow dropping `NOT NULL` on compressed tables since it is not possible to add it back without decompressing. So, if people do it expecting that they can add it back, then they might be frustrated.

That is a good point, but it is hard to do something about it. We can print a warning when we remove it, but if people actually did not want to remove it, it is too late.

2024-11-20 14:54 UTC, merged