Refresh cagg uses min value for dimension when start_time is NULL
timescale/timescaledb pull request #7546
Opened 2024-12-18 19:03 UTC by gayyappan

When the refresh_continuous_aggregate window's start is NULL, use the min value in the hypertable to determine the beginning of the range instead of the min value for the partition column.

2025-01-10 14:19 UTC, mkindahl reviewed
The description of the PR explains what is done, but it is more important why it is done. In particular:

The old behavior take the minimum value of the type when NULL is provided to create an open-ended range. What is the situation that break prompting you to do this approach instead?

2025-01-10 14:19 UTC, mkindahl commented on src/hypertable.c
> +					 quote_identifier(NameStr(ht->fd.table_name)));
This does a full table scan of the entire hypertable. With a hypertable that is big, this is going to be a significant problem, *especially* if tiering is involved.

2025-01-14 17:29 UTC, gayyappan commented on src/hypertable.c
> +					 quote_identifier(NameStr(ht->fd.table_name)));
Changed this to get min value from chunk metadata.

2025-01-15 11:16 UTC, zilder commented on src/hypertable.c
> +	appendStringInfo(command, query_str, ht->fd.id, dim->fd.id);
Is this correct arguments order? From looking at the query string it seems `dim->fd.id` should come first.

2025-01-15 11:16 UTC, zilder commented on src/hypertable.c
> +	appendStringInfo(command, query_str, ht->fd.id, dim->fd.id);
nit: `psprintf` would do the same as `StringInfo` here, but would be shorter.

2025-01-15 13:44 UTC, fabriziomello requested changes
It is not clear yet if this is the right way to solve the problem of enabling/disabling tiered read and the impacts on the caggs.

Let's please remove it from 2.18.0 milestone and discuss more.

2025-01-15 20:12 UTC, gayyappan commented
> It is not clear yet if this is the right way to solve the problem of enabling/disabling tiered read and the impacts on the caggs.
> 
> Let's please remove it from 2.18.0 milestone and discuss more.

This solves the problem only for the special case described here. And yes, we need a more general solution. This PR is meant to address the more common case (where we have bad materialization entries) and a stop gap until we implement the incremental solution.

2025-02-24 13:57 UTC, fabriziomello commented
@gayyappan @mkindahl I'll rework a bit this patch to make it more general to get the minimum open dimension when user use NULL as the refresh window start range, and it will not be tied with osm. In the future we'll implement a callback on OSM to get the minimum value from there when the `enable_tiered_reads` are on. This patch will be useful for the bathed materialization I'm working on when producing ranges over existing data.

2025-04-24 14:04 UTC, gayyappan commented
closing as a more comprehensive change will address this issue

2025-04-24 14:04 UTC, closed without merging